name: Project Automations
on:
  issues:
    types: 
      - opened
      - reopened
      - closed
    pull_request:
      types:
        - opened
        - reopened

env:
  todo: Todo
  done: Done
  in_progress: In Progress
  under_review: Under Review

jobs:
  issue_opened_or_reopened:
    name: issue_opened_or_reopened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
    steps:
      - name: Move issue to ${{ env.todo }}
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ secrets.GHPROJECT_TOKEN }}
          user: kenneth-miura
          # organization: sample-org
          project_id: 3
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.todo }} # Target status 
  issue_closed:
    name: issue_closed
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'closed'
    steps:
      - name: Moved issue to ${{env.done}}
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ secrets.GHPROJECT_TOKEN }}
          user: kenneth-miura
          # organization: sample-org
          project_id: 3
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.done }} # Target status
  pr_opened_or_reopened:
    name: pr_opened_or_reopened
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'review_requested')
    steps:
      - name: Moved PR to ${{env.under_review}}
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ secrets.GHPROJECT_TOKEN }}
          user: kenneth-miura
          # organization: sample-org
          project_id: 3
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.under_review }} # Target status
