name: Project Automations
on:
  issues:
    types: 
      - opened

env:
  todo: Todo
  done: Done
  in_progress: In Progress

jobs:
  issue_opened:
    name: issue_opened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
    steps:
      - name: Move issue to ${{ env.todo }}
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ secrets.GHPROJECT_TOKEN }}
          user: kenneth-miura
          # organization: sample-org
          project_id: 3
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.todo }} # Target status 
